// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLgfkLwScCCF6pcT8QSkSK2BSMVwjApso',
    appId: '1:327772470894:web:2c16437debf48a0b35f07f',
    messagingSenderId: '327772470894',
    projectId: 'plants-aed41',
    authDomain: 'plants-aed41.firebaseapp.com',
    storageBucket: 'plants-aed41.firebasestorage.app',
    measurementId: 'G-LQH4EFRFNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV59v_Iv2ShcltaCRW0vx_ZiELXGaFf1w',
    appId: '1:327772470894:android:a37fe68f5f3011e235f07f',
    messagingSenderId: '327772470894',
    projectId: 'plants-aed41',
    storageBucket: 'plants-aed41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvrc_196r3oWO86IdR1SemgD-pouSyCZc',
    appId: '1:327772470894:ios:16f4f9eedae15c7535f07f',
    messagingSenderId: '327772470894',
    projectId: 'plants-aed41',
    storageBucket: 'plants-aed41.firebasestorage.app',
    iosBundleId: 'com.example.plantUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvrc_196r3oWO86IdR1SemgD-pouSyCZc',
    appId: '1:327772470894:ios:16f4f9eedae15c7535f07f',
    messagingSenderId: '327772470894',
    projectId: 'plants-aed41',
    storageBucket: 'plants-aed41.firebasestorage.app',
    iosBundleId: 'com.example.plantUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLgfkLwScCCF6pcT8QSkSK2BSMVwjApso',
    appId: '1:327772470894:web:a6608bedbcb682a735f07f',
    messagingSenderId: '327772470894',
    projectId: 'plants-aed41',
    authDomain: 'plants-aed41.firebaseapp.com',
    storageBucket: 'plants-aed41.firebasestorage.app',
    measurementId: 'G-7Q9Q44STM8',
  );
}
