import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:plant_user/user/UserSplashScreen.dart';
import 'package:plant_user/user/user_register.dart';
import 'firebase_options.dart';   // generated by flutterfire configure

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'PlantPedia',
      theme: ThemeData(
        primarySwatch: Colors.green,
      ),
      home: const GreenGyaanSplashScreen(), // or your first screen
    );
  }
}
